version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: SiaNginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./site/static:/usr/share/nginx/html/static
      - ./site/media:/usr/share/nginx/html/media
    ports:
      - "8004:80"

  site:
    build:
      context: ./site
    entrypoint: ./entrypoint.sh
    container_name: SiaSite
    volumes:
      - ./site:/app
