# Generated by Django 5.0.1 on 2024-02-29 20:01

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('about', tinymce.models.HTMLField(verbose_name='about')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('text', models.TextField()),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('sdate', models.CharField(max_length=60)),
                ('edate', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('sdate', models.CharField(max_length=50)),
                ('edate', models.CharField(max_length=50)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfoilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reverse', models.BooleanField()),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', tinymce.models.HTMLField(verbose_name='description')),
                ('skills', models.CharField(max_length=100, verbose_name='skills')),
                ('site_name', models.URLField(verbose_name='site_name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Portfolio', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PL', 'Programming Lanuages'), ('LB', 'Libraries Backend'), ('FD', 'Frontend Dev'), ('LF', 'Libraries Frontend'), ('DB', 'Database'), ('TOOL', 'Tools'), ('DP', 'Document')], default='PL', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
