# Generated by Django 5.0.1 on 2024-02-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_alter_education_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='edate',
            field=models.DateField(blank=True),
        ),
    ]
