# Generated by Django 5.0.1 on 2024-02-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_alter_education_edate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='edate',
            field=models.CharField(default=22, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='sdate',
            field=models.CharField(max_length=60),
        ),
    ]
