# Generated by Django 5.0.1 on 2024-02-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_alter_education_edate_alter_education_sdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='edate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='sdate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='skill',
            field=models.CharField(max_length=100),
        ),
    ]
