# Generated by Django 5.0.1 on 2024-02-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0011_remove_experience_category_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
