# Generated by Django 5.0.1 on 2024-02-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0012_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('LANGUAGE', 'Languages'), ('LIBRARIES', 'Libraries')], default='LANGUAGE', max_length=100),
        ),
    ]
