# Generated by Django 5.0.1 on 2024-02-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0013_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoilio',
            name='skills',
            field=models.CharField(choices=[('PL', 'Programming Lanuages'), ('LB', 'Libraries Backend'), ('FD', 'Frontend Dev'), ('LF', 'Libraries Frontend'), ('DB', 'Database'), ('TOOL', 'Tools'), ('DP', 'Document')], default='ww', max_length=5, verbose_name='skills'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('PL', 'Programming Lanuages'), ('LB', 'Libraries Backend'), ('FD', 'Frontend Dev'), ('LF', 'Libraries Frontend'), ('DB', 'Database'), ('TOOL', 'Tools'), ('DP', 'Document')], default='PL', max_length=100),
        ),
    ]
