# Generated by Django 5.0.1 on 2024-02-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0014_portfoilio_skills_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoilio',
            name='skills',
            field=models.CharField(max_length=100, verbose_name='skills'),
        ),
    ]
