# Generated by Django 5.0.1 on 2024-02-29 16:40

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0016_portfoilio_reverse_alter_portfoilio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoilio',
            name='description',
            field=tinymce.models.HTMLField(default='d', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoilio',
            name='name',
            field=models.CharField(default='1', max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
    ]
