# Generated by Django 5.0.1 on 2024-02-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0017_portfoilio_description_portfoilio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
