# Generated by Django 3.2 on 2023-10-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('instagram', models.TextField()),
                ('twitter', models.TextField()),
            ],
        ),
    ]
