# Generated by Django 3.2 on 2023-10-17 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='single',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
