# Generated by Django 5.0.1 on 2024-02-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_alter_education_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='location',
            field=models.CharField(max_length=60),
        ),
    ]
