# Generated by Django 5.0.1 on 2024-02-25 15:33

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_alter_experience_edate_alter_experience_sdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
