# Generated by Django 5.0.1 on 2024-02-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0008_alter_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
