# Generated by Django 5.0.1 on 2024-02-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0009_experience_link_alter_experience_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.CharField(default='ss', max_length=100),
            preserve_default=False,
        ),
    ]
