# Generated by Django 5.0.1 on 2024-02-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0015_alter_portfoilio_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoilio',
            name='reverse',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfoilio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Portfolio', verbose_name='image'),
        ),
    ]
